package web

import "github.com/a-h/templ"

// ComponentStyles returns templ CSS components used by the web UI.
func ComponentStyles() []templ.CSSClass {
	return []templ.CSSClass{
		appFrame(),
		sidebar(),
		brand(),
		brandMark(),
		sidebarNav(),
		sidebarLink(),
		navIcon(),
		pillIcon(),
		buttonIcon(),
		sidebarFooter(),
		appMain(),
		dashboardGrid(),
		managementShell(),
		detailGrid(),
		panel(),
		sectionHeading(),
		pageTitle(),
		panelTitle(),
		eyebrow(),
		primaryButton(),
		deployForm(),
		deployButtonLoading(),
		iconButton(),
		pill(),
		identityPill(),
		statusBase(),
		statusSuccess(),
		statusWarning(),
		statusDanger(),
		field(),
		control(),
		formActions(),
		serviceEditor(),
		serviceEditorHeader(),
		tableWrap(),
		tableView(),
		tableRow(),
		tableRowAlt(),
		tableCell(),
		tableHead(),
		tableLink(),
		codeText(),
		preBlock(),
		yamlBox(),
		logOutputBox(),
		logList(),
		logLineRow(),
		logSource(),
		logMessage(),
		logJSON(),
		yamlDocument(),
		errorBox(),
	}
}
