// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func appFrame() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`grid-template-columns:14rem minmax(0, 1fr);`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:100vh;`)
	templ_7745c5c3_CSSID := templ.CSSID(`appFrame`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func sidebar() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`position:sticky;`)
	templ_7745c5c3_CSSBuilder.WriteString(`top:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:100vh;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-direction:column;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-5);`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--space-4);`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-panel);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-right:1px solid var(--border-subtle);`)
	templ_7745c5c3_CSSID := templ.CSSID(`sidebar`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func brand() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:900;`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-decoration:none;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:inherit;`)
	templ_7745c5c3_CSSID := templ.CSSID(`brand`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func brandMark() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`place-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`width:1.5rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:1.5rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-1);`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-action);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-inverse);`)
	templ_7745c5c3_CSSID := templ.CSSID(`brandMark`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func sidebarNav() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-1);`)
	templ_7745c5c3_CSSID := templ.CSSID(`sidebarNav`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func sidebarLink() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:2.25rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0 var(--space-3);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-muted);`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-decoration:none;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:800;`)
	templ_7745c5c3_CSSID := templ.CSSID(`sidebarLink`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func navIcon() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`width:1rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:1rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex:0 0 auto;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-soft);`)
	templ_7745c5c3_CSSID := templ.CSSID(`navIcon`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func pillIcon() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`width:0.95rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:0.95rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex:0 0 auto;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin-right:var(--space-1);`)
	templ_7745c5c3_CSSID := templ.CSSID(`pillIcon`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func buttonIcon() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`width:1rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:1rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`buttonIcon`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func sidebarFooter() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`margin-top:auto;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-2);`)
	templ_7745c5c3_CSSID := templ.CSSID(`sidebarFooter`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func appMain() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`width:min(92rem, 100%);`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--space-5);`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-width:0;`)
	templ_7745c5c3_CSSID := templ.CSSID(`appMain`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func dashboardGrid() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`grid-template-columns:minmax(20rem, 0.8fr) minmax(0, 1.4fr);`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-5);`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-width:0;`)
	templ_7745c5c3_CSSID := templ.CSSID(`dashboardGrid`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func managementShell() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`grid-template-columns:minmax(20rem, 0.75fr) minmax(0, 1.25fr);`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-5);`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-width:0;`)
	templ_7745c5c3_CSSID := templ.CSSID(`managementShell`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func detailGrid() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`grid-template-columns:minmax(0, 1.35fr) minmax(18rem, 0.65fr);`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-5);`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-width:0;`)
	templ_7745c5c3_CSSID := templ.CSSID(`detailGrid`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func panel() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-surface);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid var(--border-subtle);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`box-shadow:var(--shadow-panel);`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--space-5);`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-width:0;`)
	templ_7745c5c3_CSSID := templ.CSSID(`panel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func sectionHeading() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`justify-content:space-between;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:flex-start;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-3);`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin-bottom:var(--space-4);`)
	templ_7745c5c3_CSSID := templ.CSSID(`sectionHeading`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func pageTitle() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:1.5rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0 0 var(--space-4);`)
	templ_7745c5c3_CSSID := templ.CSSID(`pageTitle`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func panelTitle() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:1.08rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0;`)
	templ_7745c5c3_CSSID := templ.CSSID(`panelTitle`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func eyebrow() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`text-transform:uppercase;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.68rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:900;`)
	templ_7745c5c3_CSSBuilder.WriteString(`letter-spacing:0.08em;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-soft);`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0;`)
	templ_7745c5c3_CSSID := templ.CSSID(`eyebrow`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func primaryButton() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:2.5rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0 var(--space-4);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-action);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-inverse);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid var(--border-action);`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:800;`)
	templ_7745c5c3_CSSBuilder.WriteString(`cursor:pointer;`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-decoration:none;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`justify-content:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-2);`)
	templ_7745c5c3_CSSID := templ.CSSID(`primaryButton`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func deployForm() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0;`)
	templ_7745c5c3_CSSID := templ.CSSID(`deployForm`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func deployButtonLoading() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSID := templ.CSSID(`deployButtonLoading`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func iconButton() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`width:2.5rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:2.5rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`place-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-action);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-inverse);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid var(--border-action);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`cursor:pointer;`)
	templ_7745c5c3_CSSID := templ.CSSID(`iconButton`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func pill() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:1.75rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0 var(--space-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-pill);`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-command);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-command);`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:800;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.78rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`white-space:nowrap;`)
	templ_7745c5c3_CSSID := templ.CSSID(`pill`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func identityPill() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:1.75rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`max-width:100%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0 var(--space-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-pill);`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-subtle);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-muted);`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:800;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.78rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow:hidden;`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-overflow:ellipsis;`)
	templ_7745c5c3_CSSBuilder.WriteString(`white-space:nowrap;`)
	templ_7745c5c3_CSSID := templ.CSSID(`identityPill`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func statusBase() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:1.6rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0 var(--space-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-pill);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid currentColor;`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-transform:uppercase;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.68rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:900;`)
	templ_7745c5c3_CSSBuilder.WriteString(`letter-spacing:0.08em;`)
	templ_7745c5c3_CSSID := templ.CSSID(`statusBase`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func statusSuccess() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--success);`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--success-bg);`)
	templ_7745c5c3_CSSID := templ.CSSID(`statusSuccess`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func statusWarning() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--warning);`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--warning-bg);`)
	templ_7745c5c3_CSSID := templ.CSSID(`statusWarning`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func statusDanger() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--danger);`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--danger-bg);`)
	templ_7745c5c3_CSSID := templ.CSSID(`statusDanger`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func field() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin-bottom:var(--space-4);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-muted);`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.86rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:800;`)
	templ_7745c5c3_CSSID := templ.CSSID(`field`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func control() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`width:100%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-main);`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-input);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid var(--border-subtle);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--space-2) var(--space-3);`)
	templ_7745c5c3_CSSID := templ.CSSID(`control`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func formActions() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`justify-content:flex-end;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-2);`)
	templ_7745c5c3_CSSID := templ.CSSID(`formActions`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func serviceEditor() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-3);`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--space-4) 0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-top:1px solid var(--border-subtle);`)
	templ_7745c5c3_CSSID := templ.CSSID(`serviceEditor`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func serviceEditorHeader() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-1);`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-width:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-main);`)
	templ_7745c5c3_CSSID := templ.CSSID(`serviceEditorHeader`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func tableWrap() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`overflow-x:auto;`)
	templ_7745c5c3_CSSID := templ.CSSID(`tableWrap`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func tableView() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`width:100%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-collapse:separate;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-spacing:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-muted);`)
	templ_7745c5c3_CSSID := templ.CSSID(`tableView`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func tableRow() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-surface);`)
	templ_7745c5c3_CSSID := templ.CSSID(`tableRow`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func tableRowAlt() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-subtle);`)
	templ_7745c5c3_CSSID := templ.CSSID(`tableRowAlt`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func tableCell() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--space-3);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-bottom:1px solid var(--border-subtle);`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-align:left;`)
	templ_7745c5c3_CSSBuilder.WriteString(`vertical-align:top;`)
	templ_7745c5c3_CSSID := templ.CSSID(`tableCell`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func tableHead() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--space-3);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-bottom:1px solid var(--border-subtle);`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-align:left;`)
	templ_7745c5c3_CSSBuilder.WriteString(`vertical-align:top;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-soft);`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-transform:uppercase;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.72rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`tableHead`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func tableLink() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-main);`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-decoration:none;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:900;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-bottom:1px solid var(--border-strong);`)
	templ_7745c5c3_CSSID := templ.CSSID(`tableLink`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func codeText() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:var(--font-mono);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-mono);`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow-wrap:anywhere;`)
	templ_7745c5c3_CSSID := templ.CSSID(`codeText`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func preBlock() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:10rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow:auto;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:var(--font-mono);`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow-wrap:anywhere;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-panel);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid var(--border-subtle);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--space-3);`)
	templ_7745c5c3_CSSID := templ.CSSID(`preBlock`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func yamlBox() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`height:clamp(18rem, calc(100vh - 16rem), 46rem);`)
	templ_7745c5c3_CSSBuilder.WriteString(`max-height:max(18rem, calc(100vh - 16rem));`)
	templ_7745c5c3_CSSID := templ.CSSID(`yamlBox`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func logOutputBox() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`height:clamp(18rem, calc(100vh - 18rem), 44rem);`)
	templ_7745c5c3_CSSBuilder.WriteString(`max-height:max(18rem, calc(100vh - 18rem));`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow:auto;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-panel);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid var(--border-subtle);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-2);`)
	templ_7745c5c3_CSSID := templ.CSSID(`logOutputBox`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func logList() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-content:start;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:var(--font-mono);`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.78rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`logList`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func logLineRow() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`grid-template-columns:minmax(8rem, 0.28fr) minmax(0, 1fr);`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:var(--space-3);`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--space-2) var(--space-3);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-bottom:1px solid var(--border-subtle);`)
	templ_7745c5c3_CSSID := templ.CSSID(`logLineRow`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func logSource() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-soft);`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow-wrap:anywhere;`)
	templ_7745c5c3_CSSID := templ.CSSID(`logSource`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func logMessage() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-main);`)
	templ_7745c5c3_CSSBuilder.WriteString(`white-space:pre-wrap;`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow-wrap:anywhere;`)
	templ_7745c5c3_CSSID := templ.CSSID(`logMessage`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func logJSON() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--text-main);`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:var(--font-mono);`)
	templ_7745c5c3_CSSBuilder.WriteString(`white-space:pre-wrap;`)
	templ_7745c5c3_CSSBuilder.WriteString(`overflow-wrap:anywhere;`)
	templ_7745c5c3_CSSID := templ.CSSID(`logJSON`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func errorBox() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:var(--bg-error);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:var(--danger);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid var(--danger);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:var(--radius-2);`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:var(--space-3);`)
	templ_7745c5c3_CSSID := templ.CSSID(`errorBox`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

var _ = templruntime.GeneratedTemplate
